### PR TITLE
rrrouter: Cache

### PR DESCRIPTION
**Pull request by kallekoo**
Usage and cache behavior is described in this section of the README: https://github.com/richiefi/rrrouter/compare/kalle/ch18142/rrrouter-cache?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R206

Story details: https://app.clubhouse.io/richie/story/18142

### CODE REVIEW

**Comment by vuori777** [comment]
Generally looks good, but there are probably going to be surprises because there always are with HTTP.

  * Is the hit/miss status logged somewhere? The reason why a miss occurred would be nice to have too.
  * Differentiating on Origin always seems like it might generate a lot of duplication in some cases. Maybe do it only if response included Vary: Origin, otherwise cache only on the presence of Origin (this should handle origin servers that return ACAO: * if any Origin header is present, but don't if no Origin is present)?
  * Not directly related to caching, but having a knob to unconditionally add Access-Control-Allow-Origin to the response would probably be useful.
  * Keying directly on Accept-Encoding seems risky, because `gzip, deflate` and `deflate, gzip` will be different (I didn't see code to deal with this anyway). At least the header should be canonicalized (lowercase, sort, strip invalids), though being able to serve whatever encoding we have in cache to a client that accepts it (e.g. if we cache a gzip-encoded file based on `A-E: gzip, deflate`, also serve that to a request with `A-E: gzip`). btw how does recompression fit in here? Does it happen before or after caching the file?
  * This can be a follow-up task but supporting `stale-if-error` and `stale-while-revalidate` would be useful. Several Editions services already return these.

**Comment by markonen** [comment]
@kallekoo any comments to the issues raised by @vuori777?

**Comment by kallekoo** [comment]
> Generally looks good, but there are probably going to be surprises because there always are with HTTP.
> 
> * Is the hit/miss status logged somewhere? The reason why a miss occurred would be nice to have too.

Yea good point. I'll have it emit these at an interval.

> * Differentiating on Origin always seems like it might generate a lot of duplication in some cases. Maybe do it only if response included Vary: Origin, otherwise cache only on the presence of Origin (this should handle origin servers that return ACAO: * if any Origin header is present, but don't if no Origin is present)?
> * Not directly related to caching, but having a knob to unconditionally add Access-Control-Allow-Origin to the response would probably be useful.

Good-er points! The latter is probably then a flag `acao: <value>` in the rule config.

> * Keying directly on Accept-Encoding seems risky, because `gzip, deflate` and `deflate, gzip` will be different (I didn't see code to deal with this anyway). At least the header should be canonicalized (lowercase, sort, strip invalids), though being able to serve whatever encoding we have in cache to a client that accepts it (e.g. if we cache a gzip-encoded file based on `A-E: gzip, deflate`, also serve that to a request with `A-E: gzip`). btw how does recompression fit in here? Does it happen before or after caching the file?

Yea this canonicalization is not performed at all. I'll fix that.

Recompression is done after choosing a cache key, so `A-E: br, gzip` where the final form is `C-E: br` will not be served to clients requesting `A-E: br`. I think this can be handled alongside another ticket's requirements, https://app.clubhouse.io/richie/story/18549/rrrouter-redirect-flattening.

> * This can be a follow-up task but supporting `stale-if-error` and `stale-while-revalidate` would be useful. Several Editions services already return these.

This has been queued here: https://app.clubhouse.io/richie/story/18562/rrrouter-more-cache-features

**Comment by markonen** [comment]
@kallekoo please have a look at the current richie-edge-cache hit/miss status header our Varnish setup outputs on every request. Ideally we'd get that exact thing from rrrrouter too.

**Comment by kallekoo** [comment]
> @kallekoo please have a look at the current richie-edge-cache hit/miss status header our Varnish setup outputs on every request. Ideally we'd get that exact thing from rrrrouter too.

@markonen This is now identical, aside from "synth" not being used.

@vuori777 Acao configuration field is now available in a rule even if caching is not used.

Changing the cache key upon the origin telling us "vary: origin" is now also supported.

**Review by markonen — APPROVED** [review]

**Review by vuori777 — APPROVED** [review]

**Pull request merged**
